version: '3.3'
services:
  grafana:
    ports:
      - '3000:3000'
    container_name: grafana
    image: grafana/grafana-oss
    volumes:
      - ./data:/var/lib/grafana

networks:
  default:
    name: iot
