services:
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-goodpassword}
      PGADMIN_ENABLE_TLS: ${PGADMIN_ENABLE_TLS:-}
      PGADMIN_LISTEN_PORT: 5050
    volumes:
      - ./data:/var/lib/pgadmin
      - ./certs:/certs
      - ./config/config_system.py:/pgadmin4/config_system.py
      - ./config/servers.json:/pgadmin4/servers.json
    ports:
      - "5050:5050"
networks:
  default:
    name: postgres
    external: true
