services:
  database:
    image: "postgres"
    container_name: "postgres"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpwd
    volumes:
      - ./data:/var/lib/postgresql
    restart: unless-stopped
    ports:
      - "5432:5432"

networks:
  default:
    name: postgres

volumes:
  data:
