version: '3.3'
services:
  database:
    image: 'postgres'
    container_name: 'postgres'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data:/var/lib/postgresql/data/
    restart: unless-stopped
volumes:
  data:
