version: '2'
services:
  influxdb:
    image: influxdb:v2.1
    container_name: influxdb
    restart: unless-stopped
    ports:
      - '8086:8086'
    volumes:
      - /srv/influxdb/data:/var/lib/influxdb2
